project_id = "yjzzhfvwbnzhecffuelt"

[functions.send-email]
verify_jwt = false

[functions.ai-research]
verify_jwt = false

[functions.ai-generate-blog]
verify_jwt = false

[functions.ai-generate-image]
verify_jwt = false

[functions.ai-workflow]
verify_jwt = false

[functions.ai-analyze-topics]
verify_jwt = false

[functions.ai-auto-blog]
verify_jwt = false

[functions.ai-fetch-gsc-data]
verify_jwt = false

